[tool.poetry]
name = "talk2data"
version = "0.1.0"
description = ""
authors = ["maria <mashak.1998@gmail.com>"]
readme = "README.md"
packages = [{ include = "*" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"

# TODO: пока без TTS, его прикрутим позже, но вероятно в отдельной среде

langgraph = "1.0.0"
pydantic = "2.12.3"
python-dotenv = "1.1.1"
torch = "2.6.0"
transformers = "4.57.1"
vllm = "0.8.5"
pika = "^1.3.2"
django-environ = "^0.12.0"
numpy = "^1.26"
pandas = "^2.1"
pydantic-settings = "^2.12.0"
openai-whisper = "^20250625"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"